[Server]
Listen = ":80"
Env = "Dev"
MaxHttpRequestBody = 4

[Auth]
Secret = "U4LOTsSWEASOCXNl4lzyg0rOyGztm1so"
[Auth.Account]
    "gZmZHTdPhnnYX9PPJ0BXTl5BcxIj5hBv" = "830NOp3sbxGJQBzS9onXr0ud01mmm1Vr"

[Database]
HostPort = "tcp(172.17.0.1:3306)"
UserPassword = "root:Eu*MZO7iw6^0w7gX"
DB = "bitcoin"
[Database.Conn]
    MaxLifeTime = 600
    MaxIdle = 10
    MaxOpen = 80

[KLineData]
From = 1544889060
To = 1560614400
Duration = 5

[Strategy]
Type = "floating"
[Strategy.Floating]
    StockPos = 10000.0
    Depth = 8

[Log]
Type = "raw"

